#!/usr/bin/env node
/**
 * Regenerate public/sitemap.xml with the current catalogue.
 *
 * Run as a release step, not during the build: it needs a real Supabase
 * project, and CI builds against placeholder credentials on purpose so the
 * bundle can be verified without network access.
 *
 *   VITE_SUPABASE_URL=… VITE_SUPABASE_PUBLISHABLE_KEY=… node scripts/generate-sitemap.mjs
 *
 * Reads only public tables through the anon key, so it needs no secrets beyond
 * what the browser already ships.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SITE = process.env.SITE_URL ?? "https://havekongen.dk";
const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "sitemap.xml");

/** Routes that exist regardless of what is in the database. */
const STATIC_ROUTES = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/webshop", changefreq: "daily", priority: "0.9" },
  { path: "/havemaaler", changefreq: "monthly", priority: "0.9" },
  { path: "/havemaaler/3d", changefreq: "monthly", priority: "0.7" },
  { path: "/havekompagnon", changefreq: "monthly", priority: "0.8" },
  { path: "/dyreliv", changefreq: "monthly", priority: "0.7" },
  { path: "/ai", changefreq: "monthly", priority: "0.7" },
  { path: "/om", changefreq: "yearly", priority: "0.5" },
  { path: "/kontakt", changefreq: "yearly", priority: "0.5" },
  { path: "/levering-og-retur", changefreq: "yearly", priority: "0.4" },
  { path: "/handelsbetingelser", changefreq: "yearly", priority: "0.3" },
  { path: "/privatliv", changefreq: "yearly", priority: "0.3" },
  { path: "/cookies", changefreq: "yearly", priority: "0.3" },
];

const escapeXml = (s) =>
  String(s).replace(/[<>&'"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[c]);

async function fetchActiveProducts() {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.warn("! No Supabase credentials — writing the static routes only.");
    return [];
  }
  const url = `${SUPABASE_URL}/rest/v1/products?select=slug,updated_at&active=eq.true&order=updated_at.desc`;
  const res = await fetch(url, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  if (!res.ok) {
    console.warn(`! Could not read products (${res.status}) — writing the static routes only.`);
    return [];
  }
  return res.json();
}

const products = await fetchActiveProducts();

const entries = [
  ...STATIC_ROUTES.map((r) => ({ loc: SITE + r.path, changefreq: r.changefreq, priority: r.priority })),
  ...products.map((p) => ({
    loc: `${SITE}/webshop/${p.slug}`,
    changefreq: "weekly",
    priority: "0.8",
    lastmod: p.updated_at ? String(p.updated_at).slice(0, 10) : undefined,
  })),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/generate-sitemap.mjs. Do not edit by hand.
  Product pages are included only when the script is run with Supabase
  credentials; otherwise it emits the stable routes alone.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map(
    (e) => `  <url>
    <loc>${escapeXml(e.loc)}</loc>${e.lastmod ? `\n    <lastmod>${e.lastmod}</lastmod>` : ""}
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;

writeFileSync(OUT, xml);
console.log(`Wrote ${entries.length} URLs (${products.length} products) to public/sitemap.xml`);
