// Generated by the Supabase CLI, with one hand-made addition: the
// x-havekongen-anon header (see below). Regenerating this file will drop it.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/**
 * A stable per-browser id, sent on every request so the edge functions can hold
 * a per-visitor AI budget for signed-out callers. Without it they fall back to
 * the forwarded IP, which means a household, an office or a mobile carrier's
 * NAT would all share one quota and exhaust it for each other.
 *
 * This reads the same key `src/lib/consent.ts` writes, but deliberately does
 * not import it: consent.ts imports this module, and the cycle would leave
 * `supabase` undefined at module-evaluation time. It carries no personal data —
 * it is a random UUID, not an identifier we can resolve to a person.
 */
function anonHeader(): string {
  try {
    const KEY = 'havekongen-anon-id';
    let id = localStorage.getItem(KEY);
    if (!id) {
      id = crypto.randomUUID();
      localStorage.setItem(KEY, id);
    }
    return id;
  } catch {
    // Private mode or storage disabled — the functions fall back to the IP.
    return '';
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { 'x-havekongen-anon': anonHeader() },
  },
});
